### ISSUE TITLE
Semantic UI loaded for entire page

### ISSUE THREAD

**Issue by erquhart** [erezrokah/gitchi#4]
Need a way to scope Semantic UI to the chat widget. One way to do this is via a CSS-in-JS library like Emotion, which can accept the CSS as a string and scope it to a React component.

Here's an example where we do this with widgets that have external CSS in the CMS: https://github.com/netlify/netlify-cms/blob/ccef446d72f96fa8d8db9bf2d0be5633eff79979/packages/netlify-cms-widget-map/src/withMapControl.js#L76

**Comment by erezrokah** [comment]
Nice one! I'll take a look
